<<<<<<< HEAD
server:
  port: 8083
spring:
  application:
    name: dclound-link
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.215.26:8848
        username: nacos
        password: nacos
##配置plus打印sql日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 数据源 ds0 第一个数据库
  shardingsphere:
    datasource:
      #数据源名称
      names: ds0
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://124.222.215.26:3306/dcloud_account?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        username: root

    props:
      # 打印执行的数据库以及语句
      sql:
        show: true

=======
#server:
#  port: 8083
#spring:
#  application:
#    name: dclound-link
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 124.222.215.26:8848
#        username: nacos
#        password: nacos
###配置plus打印sql日志
##mybatis-plus:
##  configuration:
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
## 数据源 ds0 第一个数据库
#  shardingsphere:
#    datasource:
#      #数据源名称
#      names: ds0
#      ds0:
#        connectionTimeoutMilliseconds: 30000
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        idleTimeoutMilliseconds: 60000
#        jdbc-url: jdbc:mysql://124.222.215.26:3306/dcloud_link?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#        maintenanceIntervalMilliseconds: 30000
#        maxLifetimeMilliseconds: 1800000
#        maxPoolSize: 50
#        minPoolSize: 50
#        password: 123456
#        type: com.zaxxer.hikari.HikariDataSource
#        username: root
#
#    props:
#      # 打印执行的数据库以及语句
#      sql:
#        show: true
#
>>>>>>> 4d46a3bdae16dc79a90c22a7ec39b724abf92f34
