server:
  port: 8081
spring:
  application:
    name: dclound-account
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.215.26:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.215.26:3306/dcloud_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #    配置redis
  redis:
    client-type: jedis
    host: 124.222.215.26
    password: xdclass.net
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000
#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sms:
  app-code: 31efeec6a2424df3857dccd75cbd94c8
  template-id: JM1000372
#腾讯云获取https://console.cloud.tencent.com/cos/bucket
#aliyun:
#  oss:
#    endpoint: oss-cn-shanghai.aliyuncs.com
#    access-key-id: LTAI5tEJsvZrjSSYM1JyMnzd
#    access-key-secret: VO087tPHzhlJJkdfSA3ePA8wMrOaqP
#    bucketname: dcloud_link
# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tEJsvZrjSSYM1JyMnzd # 访问身份验证中用到用户标识
    accessKeySecret: VO087tPHzhlJJkdfSA3ePA8wMrOaqP # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: dcloud-short-shop # oss的存储空间
    objectName: 111.jpg

